export default {
  HOME: 'Home',
  LOGIN: 'Login',
  MAP: 'Map',
  BOTTOMTABNAVIGATOR: 'BottomTabNavigator',
  FORGOTPASSWORD: 'ForgotPassword',
  SIGNUP: 'Signup',
  EXTRASCREEN: 'ExtraScreen',
  EXTRASCREEN2: 'ExtraScreen2',
  CHECKOUT: 'Checkout',
  FIREBASE: 'Firebase',
  CALLSCREEN: 'CallScreen',
  JOINSCREEN: 'JoinScreen',
  ROOMSCREEN: 'RoomScreen',
  VIDEOCALLSCREEN: 'VideoCallScreen',
};
